# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."mysql-mysql" = {
    image = "mysql";
    environment = {
      "MYSQL_ROOT_PASSWORD" = "Q8FbKCb5hc6faeet";
    };
    ports = [
      "3306:3306/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=mysql"
      "--network=mysql_default"
    ];
  };
  systemd.services."podman-mysql-mysql" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-mysql_default.service"
    ];
    requires = [
      "podman-network-mysql_default.service"
    ];
    partOf = [
      "podman-compose-mysql-root.target"
    ];
    wantedBy = [
      "podman-compose-mysql-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-mysql_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f mysql_default";
    };
    script = ''
      podman network inspect mysql_default || podman network create mysql_default
    '';
    partOf = [ "podman-compose-mysql-root.target" ];
    wantedBy = [ "podman-compose-mysql-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-mysql-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
